# Generated by Django 5.0.1 on 2024-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_proxy', '0002_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
